USE test;

insert into `md_procurement_requisition_itemtype_department_mapping`(`item_type_id`,`item_owner_department`,`requisition_approver_department`,`requisition_reviewer_department`,`requisition_po_create_department`,`requisition_item_supplier_department`,`requisition_item_acceptor_department`) values ('CAP','EXEC','EXEC','CEO','PURC','STOR','PURC');
insert into `md_procurement_requisition_itemtype_department_mapping`(`item_type_id`,`item_owner_department`,`requisition_approver_department`,`requisition_reviewer_department`,`requisition_po_create_department`,`requisition_item_supplier_department`,`requisition_item_acceptor_department`) values ('CI','STOR','PROD','ADMI','PURC','STOR','PURC');
insert into `md_procurement_requisition_itemtype_department_mapping`(`item_type_id`,`item_owner_department`,`requisition_approver_department`,`requisition_reviewer_department`,`requisition_po_create_department`,`requisition_item_supplier_department`,`requisition_item_acceptor_department`) values ('CON','STOR','PROD','PROD','PURC','STOR','PURC');
insert into `md_procurement_requisition_itemtype_department_mapping`(`item_type_id`,`item_owner_department`,`requisition_approver_department`,`requisition_reviewer_department`,`requisition_po_create_department`,`requisition_item_supplier_department`,`requisition_item_acceptor_department`) values ('MP','MAIN','MAIN','MAIN','PURC','STOR','PURC');
insert into `md_procurement_requisition_itemtype_department_mapping`(`item_type_id`,`item_owner_department`,`requisition_approver_department`,`requisition_reviewer_department`,`requisition_po_create_department`,`requisition_item_supplier_department`,`requisition_item_acceptor_department`) values ('PM','STOR','PROD','PROD','PURC','STOR','PURC');
insert into `md_procurement_requisition_itemtype_department_mapping`(`item_type_id`,`item_owner_department`,`requisition_approver_department`,`requisition_reviewer_department`,`requisition_po_create_department`,`requisition_item_supplier_department`,`requisition_item_acceptor_department`) values ('RM','STOR','PROD','CEO','PURC','STOR','PURC');
insert into `md_procurement_requisition_itemtype_department_mapping`(`item_type_id`,`item_owner_department`,`requisition_approver_department`,`requisition_reviewer_department`,`requisition_po_create_department`,`requisition_item_supplier_department`,`requisition_item_acceptor_department`) values ('TP','TOOL','TOOL','MAIN','PURC','STOR','PURC');
insert into `md_procurement_requisition_itemtype_department_mapping`(`item_type_id`,`item_owner_department`,`requisition_approver_department`,`requisition_reviewer_department`,`requisition_po_create_department`,`requisition_item_supplier_department`,`requisition_item_acceptor_department`) values ('RMFL','STOR','PROD','ADMI','PURC','PURC','PURC');
