USE test;

insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM001','SIZE ');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM002','COLOUR');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM003','WEIGHT');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM004','DIMENSION');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM005','LENGTH  ');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM006','WIDTH  ');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM007','DIAMETER');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM008','CASE SIZE  ');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM009','THICKNESS');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM010','INNER DIAMETER  ');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM011','RA  ');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM012','MOISTURE CAPABILITY');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM013','FAT  ');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM014','SPECIFIC GRAVITY');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM015','POWDER & GRAIN');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM016','OTHERS');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM017','STABILITY CONDITION');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM018','3-PLY');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM019','HOLES');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM020','ELASICITY TEST');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM021','BORE SIZE');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM022','HELIX');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM023','SURFACE CONDITION');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM024','PURITY TEST');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM025','SEALING ');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM026','CRIMPING ');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM027','HARDNESS');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM028','LAYER WINDING');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM029','RANDOM');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM030','ELONGATION');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM031','MATERIAL ');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM032','COATING');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM033','CHEMICAL');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM034','UTS');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM035','GRAIN SIZE');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM036','PH');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM037','COPPER LEVEL');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM038','LEVEL');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM039','TEXTURE');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM040','DENSITY');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM041','CUTTING');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM042','PRINTING');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM043','INNER POLY COAT');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM044','PELLET');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM045','GRADE');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM046','OUTER DIAMETER');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM047','CAST');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM481','shape');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('','abc');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('QPARAM0101','test param');
insert into `md_quality_quality_parameter`(`quality_parameter_id`,`quality_parameter_name`) values ('','s');
