USE test;

insert into `od_inward_item_register`(`supplier_id`,`inward_register_number`,`item_id`,`container_id`,`unit_of_measure_id`,`remarks`,`container_quantity`,`item_quantity`,`status`,`po_number`,`po_date`,`accepted_container_quantity`,`accepted_item_quantity`) values ('sup001','irn259','TAT02','box','tonne','gud','2','2',null,null,null,null,null);
insert into `od_inward_item_register`(`supplier_id`,`inward_register_number`,`item_id`,`container_id`,`unit_of_measure_id`,`remarks`,`container_quantity`,`item_quantity`,`status`,`po_number`,`po_date`,`accepted_container_quantity`,`accepted_item_quantity`) values ('TAT','irn262','WIR02','coil','tonne','good','2','1',null,null,null,null,null);
insert into `od_inward_item_register`(`supplier_id`,`inward_register_number`,`item_id`,`container_id`,`unit_of_measure_id`,`remarks`,`container_quantity`,`item_quantity`,`status`,`po_number`,`po_date`,`accepted_container_quantity`,`accepted_item_quantity`) values ('NAT','irn263','WIR07','coil','tonne','fair','2','3',null,null,null,null,null);
insert into `od_inward_item_register`(`supplier_id`,`inward_register_number`,`item_id`,`container_id`,`unit_of_measure_id`,`remarks`,`container_quantity`,`item_quantity`,`status`,`po_number`,`po_date`,`accepted_container_quantity`,`accepted_item_quantity`) values ('MUK','irn264','WIR03','coil','tonne','gud','2','3','stores_history',null,null,null,null);
insert into `od_inward_item_register`(`supplier_id`,`inward_register_number`,`item_id`,`container_id`,`unit_of_measure_id`,`remarks`,`container_quantity`,`item_quantity`,`status`,`po_number`,`po_date`,`accepted_container_quantity`,`accepted_item_quantity`) values ('sup001','irn265','TAT02','box','tonne','gud','2','3','stores',null,null,null,null);
insert into `od_inward_item_register`(`supplier_id`,`inward_register_number`,`item_id`,`container_id`,`unit_of_measure_id`,`remarks`,`container_quantity`,`item_quantity`,`status`,`po_number`,`po_date`,`accepted_container_quantity`,`accepted_item_quantity`) values ('sup001','irn630','TAT02','box','tonne','good','1','2','stores',null,null,null,null);
insert into `od_inward_item_register`(`supplier_id`,`inward_register_number`,`item_id`,`container_id`,`unit_of_measure_id`,`remarks`,`container_quantity`,`item_quantity`,`status`,`po_number`,`po_date`,`accepted_container_quantity`,`accepted_item_quantity`) values ('MUK','irn264','WIR03','coil','tonne','gud','2','3','quality_history','pono6655','22/5/17','20','2');
insert into `od_inward_item_register`(`supplier_id`,`inward_register_number`,`item_id`,`container_id`,`unit_of_measure_id`,`remarks`,`container_quantity`,`item_quantity`,`status`,`po_number`,`po_date`,`accepted_container_quantity`,`accepted_item_quantity`) values ('MUK','irn264','WIR03','coil','tonne','gud','2','3','purchase','pono6655','22/5/17','31','2');
