USE test;

insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','9999','irn24',null,'btno22','1');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','con7','irn24',null,'btno23','1');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','con1','irn24',null,'btno73','10');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','con2','irn24',null,'btno74','20');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values (null,null,null,null,null,null);
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values (null,null,null,null,null,null);
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','9999','irn24','','btno22','1');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','con7','irn24','','btno23','1');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','9999','irn24','','btno22','1');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','con7','irn24','','btno23','1');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','9999','irn24','','btno22','1');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','con7','irn24','','btno23','1');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','9999','irn24','','btno22','1');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','con7','irn24','','btno23','1');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','9999','irn24','','btno22','1');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','con7','irn24','','btno23','1');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','110011','irn264','2222','btno538','10');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','220022','irn264','3333','btno539','30');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','330033','irn264','4444','btno542','30');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','330033','irn264','4444','btno542','30');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','330033','irn264','4444','btno542','30');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','12345','irn264','555','btno552','12');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','11222','irn264','333','btno554','10');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','445555','irn264','333','btno554','10');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','234324','irn264','5677','btno557','21');
insert into `od_item_container_detail`(`container_id`,`container_number`,`inward_register_number`,`heat_number`,`batch_number`,`quantity`) values ('coil','324234','irn264','5666','btno558','10');
