USE test;

insert into `od_purchase_purchase_register`(`purchase_order_number`,`purchase_order_date`,`purchase_order_type_id`,`item_id`,`item_quantity`,`warehouse_stores_id`,`status`,`supplier_id`,`reference_id`,`po_price`) values ('123','2017-05-27','PM','PAC02','100','stores2','order created','SUP','int583','1.25');
insert into `od_purchase_purchase_register`(`purchase_order_number`,`purchase_order_date`,`purchase_order_type_id`,`item_id`,`item_quantity`,`warehouse_stores_id`,`status`,`supplier_id`,`reference_id`,`po_price`) values ('2222','2017-05-27','PM','PAC02','10','stores2','order created','SUP','int583','1.25');
insert into `od_purchase_purchase_register`(`purchase_order_number`,`purchase_order_date`,`purchase_order_type_id`,`item_id`,`item_quantity`,`warehouse_stores_id`,`status`,`supplier_id`,`reference_id`,`po_price`) values ('5555','2017-05-27','PM','PAC02','890','stores2','order created','SUP','int583','0');
insert into `od_purchase_purchase_register`(`purchase_order_number`,`purchase_order_date`,`purchase_order_type_id`,`item_id`,`item_quantity`,`warehouse_stores_id`,`status`,`supplier_id`,`reference_id`,`po_price`) values ('6666','2017-05-27','PM','PAC02','1000','stores2','order created','SUP','int583','1.25');
insert into `od_purchase_purchase_register`(`purchase_order_number`,`purchase_order_date`,`purchase_order_type_id`,`item_id`,`item_quantity`,`warehouse_stores_id`,`status`,`supplier_id`,`reference_id`,`po_price`) values ('','2017-05-27','PM','PAC02','1000','stores2','order created','SUP','int583','2');
insert into `od_purchase_purchase_register`(`purchase_order_number`,`purchase_order_date`,`purchase_order_type_id`,`item_id`,`item_quantity`,`warehouse_stores_id`,`status`,`supplier_id`,`reference_id`,`po_price`) values ('','2017-05-27','PM','PAC02','1000','stores2','order created','SUP','int583','2');
insert into `od_purchase_purchase_register`(`purchase_order_number`,`purchase_order_date`,`purchase_order_type_id`,`item_id`,`item_quantity`,`warehouse_stores_id`,`status`,`supplier_id`,`reference_id`,`po_price`) values ('123','2017-05-27','PM','PAC02','1000','stores2','order created','SUP','int583','2');
insert into `od_purchase_purchase_register`(`purchase_order_number`,`purchase_order_date`,`purchase_order_type_id`,`item_id`,`item_quantity`,`warehouse_stores_id`,`status`,`supplier_id`,`reference_id`,`po_price`) values ('12121313','2017-05-30','PM','PAC02','1000','stores2','order created','SUP','int583','2');
insert into `od_purchase_purchase_register`(`purchase_order_number`,`purchase_order_date`,`purchase_order_type_id`,`item_id`,`item_quantity`,`warehouse_stores_id`,`status`,`supplier_id`,`reference_id`,`po_price`) values ('12345','2017-05-30','PM','PAC02','1000','stores2','order created','SUP','int583','2');
