USE test;

insert into `od_sales_sales_order_detail`(`salesorder_id`,`salesorder_date`,`customer_id`,`item_id`,`item_description`,`item_specification`,`container_quantity`,`order_quantity`,`delivered_quantity`,`required_delivery_date`,`status`,`emp_id`) values ('1','20-04-2017','CUS0001','FCWO1','good','wire','1000','600','900','28-03-17','Order placed','purchase');
insert into `od_sales_sales_order_detail`(`salesorder_id`,`salesorder_date`,`customer_id`,`item_id`,`item_description`,`item_specification`,`container_quantity`,`order_quantity`,`delivered_quantity`,`required_delivery_date`,`status`,`emp_id`) values ('2','19-02-2017','cus1','FLUX02','wire','5.5 inch','2','700','90','21-05-1017','fullfilled','3');
insert into `od_sales_sales_order_detail`(`salesorder_id`,`salesorder_date`,`customer_id`,`item_id`,`item_description`,`item_specification`,`container_quantity`,`order_quantity`,`delivered_quantity`,`required_delivery_date`,`status`,`emp_id`) values ('3','29-02-2017','CUS0007','WIR02','rod','5.5 inch','2','800','90','26-05-1017','Order placed','3');
insert into `od_sales_sales_order_detail`(`salesorder_id`,`salesorder_date`,`customer_id`,`item_id`,`item_description`,`item_specification`,`container_quantity`,`order_quantity`,`delivered_quantity`,`required_delivery_date`,`status`,`emp_id`) values ('4','13-02-2017','CUS0007','MIG01','metal','5.5 inch','2','1000','90','9-05-1017','Order placed','ceo');
insert into `od_sales_sales_order_detail`(`salesorder_id`,`salesorder_date`,`customer_id`,`item_id`,`item_description`,`item_specification`,`container_quantity`,`order_quantity`,`delivered_quantity`,`required_delivery_date`,`status`,`emp_id`) values ('3','29-02-2017','CUS0007','WIR02','wire','5.5 inch','2','800','90','7-05-1017','Created','3');
insert into `od_sales_sales_order_detail`(`salesorder_id`,`salesorder_date`,`customer_id`,`item_id`,`item_description`,`item_specification`,`container_quantity`,`order_quantity`,`delivered_quantity`,`required_delivery_date`,`status`,`emp_id`) values ('2','19-02-2017','cus1','FLUX02','wire','5.5 inch','2','700','90','21-05-1017','fullfilled','3');
insert into `od_sales_sales_order_detail`(`salesorder_id`,`salesorder_date`,`customer_id`,`item_id`,`item_description`,`item_specification`,`container_quantity`,`order_quantity`,`delivered_quantity`,`required_delivery_date`,`status`,`emp_id`) values ('sal315','2017-05-20','CUS0007','MIG01','undefined','undefined','200','1200','undefined','2017-05-18','partially fullfilled','3');
insert into `od_sales_sales_order_detail`(`salesorder_id`,`salesorder_date`,`customer_id`,`item_id`,`item_description`,`item_specification`,`container_quantity`,`order_quantity`,`delivered_quantity`,`required_delivery_date`,`status`,`emp_id`) values ('sal328','2017-05-20','CUS0011','MIG01','','wire','300','500','undefined','2017-05-16','Order placed','3');
insert into `od_sales_sales_order_detail`(`salesorder_id`,`salesorder_date`,`customer_id`,`item_id`,`item_description`,`item_specification`,`container_quantity`,`order_quantity`,`delivered_quantity`,`required_delivery_date`,`status`,`emp_id`) values ('sal393','2017-05-22','CUS0007','FLUX01','undefined','undefined','200','1200','undefined','2017-05-23','Created','3');
insert into `od_sales_sales_order_detail`(`salesorder_id`,`salesorder_date`,`customer_id`,`item_id`,`item_description`,`item_specification`,`container_quantity`,`order_quantity`,`delivered_quantity`,`required_delivery_date`,`status`,`emp_id`) values ('sal768','2017-05-26','CUS0007','MIG01','undefined','undefined','1000','1000','undefined','2017-05-24','Created','stores');
insert into `od_sales_sales_order_detail`(`salesorder_id`,`salesorder_date`,`customer_id`,`item_id`,`item_description`,`item_specification`,`container_quantity`,`order_quantity`,`delivered_quantity`,`required_delivery_date`,`status`,`emp_id`) values ('sal834','2017-05-27','CUS0007','MIG01','','wire','500','700','undefined','2017-05-16','Created','stores');
insert into `od_sales_sales_order_detail`(`salesorder_id`,`salesorder_date`,`customer_id`,`item_id`,`item_description`,`item_specification`,`container_quantity`,`order_quantity`,`delivered_quantity`,`required_delivery_date`,`status`,`emp_id`) values ('sal865','2017-05-30','CUS0007','SAW01','','spec1','2000','2000','undefined','2017-05-16','Created',null);
