USE test;

insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('1','call-add-customer','Add Customer');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('5','vehicle-in-process','vehicle in process');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('5','call-security-card','security');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('6','vehicleorder-summary','vehicleorder-summary');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('11','grn-stores','stores');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('12','grn-purchase','purchase');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('22','grn-quality','quality');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('2','call-add-item','Create Item');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('10','vehicle-in-process','vehicle in process');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('7','specification-in-detail','Specifications');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('9','call-add-supplier','Add Supplier');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('15','shopping-category','Shopping');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('10','call-ceo-card','New Items');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('16','quality-testing-process','Quality testing');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('29','requisition-process','Create Requisition');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('3','salesorder-summary','salesorder summary');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('4','sales-projection','sales projection');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('8','salesorder-projection','salesorder projection');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('14','salesorder-summary-logistics','salesorder summary logistics');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('36','call-purchase-request-approval','Approve Purchase Request');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('13','sales-order','sales order');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('3','salesprojection-summary','salesprojection summary');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('34','purchase-request-process','Create Purchase Request');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('35','call-requisition-approval','New Requisition');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('37','purchase-order','Create Purchase Order');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('38','requisition-stores','Requisition');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('45','stores-salesorder-summary','stores salesorder summary');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('46','stores-salesorder','stores salesorder');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('47','stores-salesorder-summary-logistics','stores salesorder summary logistics');
insert into `service_config_login_menu`(`menu_id`,`ui_component`,`ui_menuname`) values ('50','test-file','demo test');
